export type Section = {
  type: "h2" | "h3" | "p" | "ul" | "tip";
  content: string | string[];
};

export type Post = {
  slug: string;
  title: string;
  description: string;
  date: string;
  category: string;
  readTime: string;
  sections: Section[];
};

export const posts: Post[] = [
  {
    slug: "optimiser-fiche-google-my-business-2026",
    title: "Comment optimiser sa fiche Google My Business en 2026 (guide complet)",
    description: "Découvrez toutes les étapes pour optimiser votre fiche Google My Business et dominer le référencement local en 2026. Photos, horaires, avis, catégories : tout ce qu'il faut savoir.",
    date: "2026-03-20",
    category: "Optimisation GMB",
    readTime: "9 min",
    sections: [
      { type: "p", content: "Google My Business (désormais appelé Google Business Profile) est l'outil le plus puissant pour attirer des clients locaux. Une fiche bien optimisée apparaît en tête des résultats sur Google Maps et dans le pack local — ces 3 résultats mis en avant avant même les résultats organiques. Voici comment l'optimiser au maximum en 2026." },
      { type: "h2", content: "Pourquoi optimiser votre fiche Google My Business ?" },
      { type: "p", content: "46% des recherches Google ont une intention locale. Quand un client cherche 'restaurant bordeaux' ou 'plombier près de chez moi', c'est votre fiche GMB qui décide si vous apparaissez ou non. Une fiche complète reçoit en moyenne 7 fois plus de clics qu'une fiche incomplète." },
      { type: "h2", content: "1. Complétez 100% des informations de base" },
      { type: "p", content: "La première étape est de remplir chaque champ disponible : nom exact de l'entreprise, adresse précise, numéro de téléphone, site web, horaires d'ouverture (y compris les jours fériés). Google privilégie les fiches complètes dans ses algorithmes de classement local." },
      { type: "ul", content: ["Nom de l'entreprise : utilisez votre nom commercial exact, sans mots clés artificiels", "Adresse : vérifiez qu'elle correspond exactement à votre adresse réelle", "Téléphone : utilisez un numéro local (pas un 0800 ou numéro surtaxé)", "Horaires : mettez-les à jour pour les jours fériés et vacances", "Site web : liez vers votre page d'accueil ou une page locale dédiée"] },
      { type: "h2", content: "2. Choisissez les bonnes catégories" },
      { type: "p", content: "La catégorie principale est le signal le plus fort envoyé à Google. Choisissez la catégorie la plus précise possible. Si vous êtes pizzeria, sélectionnez 'Pizzeria' plutôt que 'Restaurant'. Vous pouvez ajouter jusqu'à 9 catégories secondaires — utilisez-les pour couvrir toutes vos activités." },
      { type: "tip", content: "Astuce : regardez les catégories utilisées par vos concurrents qui apparaissent en premier sur Google Maps. C'est souvent une indication des catégories les plus efficaces dans votre secteur." },
      { type: "h2", content: "3. Optimisez votre description d'entreprise" },
      { type: "p", content: "La description (750 caractères max) est votre chance d'expliquer ce qui vous différencie. Intégrez naturellement vos mots clés principaux : votre activité, votre ville, vos spécialités. Évitez le bourrage de mots clés — écrivez pour vos clients, pas pour l'algorithme." },
      { type: "h2", content: "4. Publiez des photos de qualité régulièrement" },
      { type: "p", content: "Les fiches avec photos reçoivent 42% de demandes d'itinéraires en plus et 35% de clics vers le site web supplémentaires. Publiez des photos de votre devanture, intérieur, équipe, produits et services. L'idéal est d'ajouter au moins une nouvelle photo par semaine — la fraîcheur du contenu est un facteur de classement." },
      { type: "ul", content: ["Photo de couverture : choisissez une image représentative et attrayante", "Logo : utilisez votre logo officiel en haute résolution", "Photos de l'établissement : extérieur, intérieur, ambiance", "Photos de produits/services : montrez ce que vous proposez", "Photos d'équipe : humanisez votre entreprise"] },
      { type: "h2", content: "5. Collectez et répondez à tous vos avis" },
      { type: "p", content: "Les avis Google sont le facteur numéro 1 du référencement local. Une note élevée et un grand nombre d'avis récents propulsent votre fiche en tête. Mais attention : Google surveille aussi la régularité. Obtenir 50 avis en une semaine puis rien pendant 6 mois est suspect." },
      { type: "p", content: "Répondez à tous les avis, positifs comme négatifs. Une réponse professionnelle à un avis négatif montre que vous prenez soin de vos clients et peut retourner l'image négative en démonstration de sérieux." },
      { type: "h2", content: "6. Utilisez les Google Posts régulièrement" },
      { type: "p", content: "Les Google Posts sont des mini-publications visibles directement sur votre fiche. Utilisez-les pour annoncer des promotions, événements, nouveaux produits ou actualités. Publiez au minimum 2 fois par mois pour signaler à Google que votre fiche est active." },
      { type: "h2", content: "7. Activez les messages et questions/réponses" },
      { type: "p", content: "La fonctionnalité de messagerie permet aux clients de vous contacter directement depuis Google. Activez-la et répondez rapidement — Google affiche votre temps de réponse moyen. La section Q&R permet aussi de pré-remplir les questions fréquentes : prenez le contrôle en posant vous-même les questions importantes et en y répondant." },
      { type: "h2", content: "Conclusion : l'optimisation GMB est un travail continu" },
      { type: "p", content: "L'algorithme local de Google récompense la régularité et la complétude. Une fiche optimisée une fois puis abandonnée perdra progressivement sa position. Utilisez un outil comme Klevano pour suivre votre score d'optimisation, recevoir des alertes sur les nouveaux avis et maintenir votre fiche au top sans y passer des heures chaque semaine." },
    ],
  },
  {
    slug: "obtenir-plus-avis-google-entreprise",
    title: "Comment obtenir plus d'avis Google pour votre entreprise (méthodes qui marchent)",
    description: "Les meilleures stratégies pour collecter plus d'avis Google 5 étoiles légalement et efficacement. Augmentez votre note et boostez votre visibilité locale.",
    date: "2026-03-25",
    category: "Collecte d'avis",
    readTime: "7 min",
    sections: [
      { type: "p", content: "Les avis Google sont la monnaie du référencement local. Une entreprise avec 200 avis à 4,7 étoiles écrase systématiquement un concurrent avec 20 avis à 5 étoiles. Mais comment obtenir plus d'avis sans violer les conditions d'utilisation de Google ? Voici les méthodes qui fonctionnent vraiment." },
      { type: "h2", content: "Pourquoi les avis Google sont-ils si importants ?" },
      { type: "p", content: "Google utilise 3 facteurs principaux pour le classement local : la pertinence (votre activité correspond-elle à la recherche ?), la distance, et la notoriété. Les avis clients constituent la principale mesure de notoriété. Plus vous avez d'avis récents et positifs, plus Google vous pousse en avant." },
      { type: "ul", content: ["93% des consommateurs lisent les avis avant de choisir un commerce local", "Un passage de 3,5 à 3,7 étoiles augmente les conversions de 120%", "Les entreprises avec plus de 100 avis ont 5x plus de clics que celles avec moins de 10 avis", "Les avis récents comptent plus que les anciens"] },
      { type: "h2", content: "1. Demandez au bon moment" },
      { type: "p", content: "Le timing est crucial. La meilleure fenêtre pour demander un avis est immédiatement après une expérience positive : à la fin d'un repas, après la livraison d'un service, lors du paiement. Plus vous attendez, moins le client est susceptible de laisser un avis." },
      { type: "tip", content: "La règle d'or : demandez en personne d'abord ('Avez-vous été satisfait ?'), puis envoyez le lien par SMS ou email dans les 2 heures qui suivent." },
      { type: "h2", content: "2. Simplifiez au maximum le processus" },
      { type: "p", content: "Chaque étape supplémentaire entre votre demande et l'avis publié divise par 2 votre taux de conversion. Créez un lien direct vers votre page d'avis Google et raccourcissez-le. Mieux encore, utilisez un QR code que vous placez sur vos tables, comptoirs, tickets de caisse ou packaging." },
      { type: "h2", content: "3. Utilisez un système de collecte intelligent" },
      { type: "p", content: "Les outils de collecte d'avis modernes comme Klevano permettent de filtrer les expériences : les clients satisfaits (4-5 étoiles) sont redirigés vers Google, tandis que les insatisfaits (1-3 étoiles) laissent un feedback privé que vous pouvez traiter en interne. Résultat : votre note Google monte, et vous évitez les mauvais avis publics." },
      { type: "h2", content: "4. Formez votre équipe" },
      { type: "p", content: "Vos employés sont vos meilleurs ambassadeurs. Formez-les à mentionner naturellement les avis dans leurs échanges avec les clients : 'Si vous avez été satisfait, un petit avis Google nous aiderait beaucoup.' Une phrase simple, non intrusive, dite avec sincérité, convertit souvent mieux qu'un email automatique." },
      { type: "h2", content: "5. Répondez à tous vos avis existants" },
      { type: "p", content: "Répondre aux avis (positifs et négatifs) montre aux futurs clients que vous êtes attentif et professionnel. Cela encourage aussi les clients satisfaits à laisser leur avis en voyant que vous y accordez de l'importance. Google prend également en compte l'engagement du propriétaire dans ses algorithmes." },
      { type: "h2", content: "Ce qu'il ne faut JAMAIS faire" },
      { type: "ul", content: ["Acheter des faux avis : Google les détecte et peut supprimer votre fiche", "Offrir des avantages en échange d'avis positifs : interdit par les CGU Google", "Demander à vos employés de laisser des avis : Google peut les supprimer", "Envoyer des centaines de demandes d'un coup : la régularité est préférable"] },
      { type: "h2", content: "Conclusion : la régularité avant tout" },
      { type: "p", content: "Obtenir 5 avis par mois de façon régulière vaut mieux que 50 avis en un mois puis rien. Mettez en place un système simple et reproductible : lien QR code à la caisse, email automatique post-achat, formation de votre équipe. Avec Klevano, ce processus est entièrement automatisé et filtré pour maximiser votre note." },
    ],
  },
  {
    slug: "erreurs-referencement-local-google",
    title: "Les 8 erreurs qui tuent votre référencement local sur Google",
    description: "Évitez ces erreurs critiques qui empêchent votre entreprise d'apparaître dans Google Maps et les résultats locaux. Guide pratique pour les commerces et artisans.",
    date: "2026-03-28",
    category: "Référencement local",
    readTime: "8 min",
    sections: [
      { type: "p", content: "Vous avez une fiche Google My Business mais votre entreprise n'apparaît pas dans les résultats locaux ? Vous êtes probablement en train de commettre une ou plusieurs de ces erreurs fatales. Le référencement local est un domaine précis avec ses propres règles — voici les pièges à éviter absolument." },
      { type: "h2", content: "Erreur #1 : Informations incohérentes (NAP)" },
      { type: "p", content: "Le NAP (Name, Address, Phone) doit être exactement identique partout sur le web : votre fiche GMB, votre site web, les annuaires, les réseaux sociaux. Si votre adresse s'écrit '15 rue de la Paix' sur Google et '15, Rue de la Paix' sur votre site, Google considère que ce sont deux entités différentes et pénalise votre classement." },
      { type: "tip", content: "Vérifiez vos informations sur les principaux annuaires : Pages Jaunes, Yelp, TripAdvisor, Foursquare. La cohérence est un signal de confiance fort pour Google." },
      { type: "h2", content: "Erreur #2 : Fiche non vérifiée" },
      { type: "p", content: "Une fiche non vérifiée a très peu de chance d'apparaître dans le pack local. La vérification (par courrier, téléphone ou vidéo) prouve à Google que vous êtes bien le propriétaire de l'établissement. C'est la première chose à faire avant toute optimisation." },
      { type: "h2", content: "Erreur #3 : Catégorie principale mal choisie" },
      { type: "p", content: "La catégorie principale est le signal le plus fort que vous envoyez à Google. Choisir 'Commerce de détail' quand vous êtes 'Boulangerie artisanale' vous fait perdre des positions sur toutes les recherches spécifiques. Soyez précis." },
      { type: "h2", content: "Erreur #4 : Aucune photo ou photos de mauvaise qualité" },
      { type: "p", content: "Les fiches sans photos ou avec des photos floues et démodées inspirent peu confiance. Google favorise les fiches avec des photos récentes et nombreuses. Une photo de 2015 de votre devanture ne suffit pas — publiez du contenu visuel frais régulièrement." },
      { type: "h2", content: "Erreur #5 : Ignorer les avis négatifs" },
      { type: "p", content: "Ne pas répondre aux avis négatifs est une double erreur. D'abord, ça donne l'impression aux futurs clients que vous vous en fichez. Ensuite, une réponse professionnelle peut transformer un avis négatif en démonstration de votre sérieux. Répondez toujours dans les 48h." },
      { type: "h2", content: "Erreur #6 : Horaires incorrects ou non mis à jour" },
      { type: "p", content: "Si un client se déplace suite à vos horaires Google et trouve votre établissement fermé, c'est une expérience négative qui génère souvent un avis 1 étoile. Mettez à jour vos horaires pour chaque jour férié, congés annuels et événements spéciaux." },
      { type: "h2", content: "Erreur #7 : Pas de Google Posts" },
      { type: "p", content: "Les Google Posts signalent à l'algorithme que votre fiche est active et maintenue. Une fiche sans publication depuis 3 mois est considérée comme 'inactive'. Publiez au moins 2 fois par mois : promotions, actualités, nouveaux produits, événements." },
      { type: "h2", content: "Erreur #8 : Mots clés dans le nom d'entreprise" },
      { type: "p", content: "Ajouter des mots clés dans votre nom Google My Business ('Plombier Paris - Jean Dupont') est une violation des conditions d'utilisation de Google. Non seulement votre fiche risque d'être suspendue, mais Google le détecte de plus en plus facilement. Utilisez votre vrai nom commercial." },
      { type: "h2", content: "Comment éviter toutes ces erreurs d'un coup ?" },
      { type: "p", content: "Klevano analyse automatiquement votre fiche GMB et identifie toutes ces erreurs via son système de scoring en 8 points. Vous recevez une liste d'actions prioritaires avec des explications claires. Plus besoin de deviner — vous savez exactement quoi corriger pour progresser dans les classements locaux." },
    ],
  },
  {
    slug: "referencement-local-restaurant-commerce",
    title: "Référencement local pour restaurants et commerces : le guide 2026",
    description: "Guide complet du référencement local pour restaurants, cafés, boutiques et artisans. Comment apparaître en premier sur Google Maps et attirer plus de clients locaux.",
    date: "2026-04-01",
    category: "Référencement local",
    readTime: "10 min",
    sections: [
      { type: "p", content: "Le référencement local est devenu la priorité numéro 1 pour les commerces de proximité. Avec 76% des recherches mobiles 'près de chez moi' qui aboutissent à une visite en magasin dans les 24h, apparaître en tête de Google Maps peut littéralement transformer votre activité." },
      { type: "h2", content: "Qu'est-ce que le référencement local ?" },
      { type: "p", content: "Le référencement local (ou SEO local) désigne l'ensemble des techniques pour apparaître dans les résultats de recherche géolocalisés. Il comprend le pack local (les 3 établissements mis en avant avec carte), Google Maps, et les résultats organiques avec indication géographique." },
      { type: "h2", content: "Les 3 facteurs de classement local selon Google" },
      { type: "ul", content: ["Pertinence : votre activité correspond-elle à ce que l'utilisateur cherche ?", "Distance : êtes-vous géographiquement proche de l'utilisateur ?", "Notoriété : êtes-vous reconnu comme un acteur fiable dans votre secteur ?"] },
      { type: "p", content: "La pertinence et la notoriété sont les deux leviers sur lesquels vous pouvez agir. La distance dépend de votre localisation géographique — vous ne pouvez pas la changer, mais vous pouvez compenser en étant excellent sur les deux autres facteurs." },
      { type: "h2", content: "Stratégie pour les restaurants" },
      { type: "p", content: "Pour un restaurant, les recherches clés sont : '[type de cuisine] [ville]', 'restaurant pas cher [quartier]', 'restaurant ouvert maintenant [ville]'. Votre fiche GMB doit mentionner votre cuisine, votre quartier, vos spécialités dans la description et les catégories." },
      { type: "ul", content: ["Publiez des photos de vos plats chaque semaine", "Répondez à chaque avis, surtout les négatifs", "Utilisez l'attribut 'Menu' pour lister vos plats directement sur GMB", "Activez la réservation en ligne via Google (Reserve with Google)", "Publiez vos événements spéciaux (soirées, menus du jour) via Google Posts"] },
      { type: "h2", content: "Stratégie pour les commerces et boutiques" },
      { type: "p", content: "Pour un commerce, les recherches sont : '[produit] [ville]', '[type de boutique] près de moi', 'magasin [produit] ouvert dimanche'. Votre fiche doit clairement indiquer vos produits, vos marques et vos services." },
      { type: "ul", content: ["Ajoutez votre catalogue produits sur GMB (fonction Produits)", "Précisez si vous proposez click & collect, livraison ou retrait en magasin", "Utilisez les attributs : paiement CB, parking, accès PMR...", "Publiez des promotions via Google Posts", "Encouragez les avis avec mention de vos produits spécifiques"] },
      { type: "h2", content: "Stratégie pour les artisans et professions libérales" },
      { type: "p", content: "Pour un artisan (plombier, électricien, coiffeur...) ou professionnel libéral (médecin, avocat...), les recherches sont souvent urgentes : '[métier] [ville] urgent', '[métier] disponible maintenant'. La réactivité et les avis récents sont primordiaux." },
      { type: "ul", content: ["Activez la messagerie Google pour les demandes urgentes", "Mentionnez votre zone d'intervention dans la description", "Mettez en avant vos certifications et qualifications", "Répondez aux devis Google (disponible pour certains secteurs)", "Publiez des photos de vos réalisations récentes"] },
      { type: "h2", content: "L'importance des avis pour le référencement local" },
      { type: "p", content: "Les avis sont le carburant du référencement local. Google Mapsaffiche en premier les établissements avec le plus d'avis récents et la meilleure note. Un commerce avec 150 avis à 4,6 étoiles battra presque toujours un concurrent à 5 étoiles avec 8 avis." },
      { type: "tip", content: "Objectif minimum : 50 avis avec une note supérieure à 4,3/5 pour commencer à apparaître systématiquement dans le pack local de votre ville." },
      { type: "h2", content: "Mesurer et améliorer votre référencement local" },
      { type: "p", content: "Google My Business fournit des statistiques précieuses : nombre de recherches, d'appels, de demandes d'itinéraires, de clics vers votre site. Suivez ces métriques chaque mois pour mesurer l'impact de vos actions. Avec Klevano, vous disposez d'un tableau de bord qui centralise toutes ces données et vous suggère les actions prioritaires pour progresser." },
    ],
  },
  {
    slug: "referencement-local-restaurant-cafe",
    title: "Référencement local pour restaurant et café : attirer plus de clients en 2026",
    description: "Comment dominer Google Maps quand on est restaurateur ou gérant d'un café. Stratégies concrètes pour augmenter vos réservations et votre visibilité locale.",
    date: "2026-04-01",
    category: "Référencement local",
    readTime: "8 min",
    sections: [
      { type: "p", content: "Pour un restaurant ou un café, Google Maps est votre vitrine numéro un. Quand un client cherche 'restaurant bordeaux centre' ou 'café brunch lyon', ce sont les 3 premiers résultats sur Google Maps qui raflent 90% des clics. Si vous n'êtes pas dans ce trio, vous êtes invisible — peu importe la qualité de votre cuisine." },
      { type: "h2", content: "Pourquoi le référencement local est crucial en restauration" },
      { type: "p", content: "76% des personnes qui font une recherche locale sur mobile visitent un commerce dans les 24h. En restauration, ce délai est souvent de moins d'une heure : le client a faim maintenant. Votre fiche Google My Business doit donc être irréprochable pour capter ces clients au moment exact où ils cherchent." },
      { type: "ul", content: ["Le 'pack local' (3 premiers résultats Maps) reçoit 44% des clics totaux", "Les restaurants avec plus de 100 avis ont 5x plus de visites Maps", "Une mauvaise photo de couverture réduit le taux de clic de 35%", "Les horaires incorrects = la cause n°1 d'avis négatifs évitables"] },
      { type: "h2", content: "Optimiser votre fiche pour les recherches 'restaurant [ville]'" },
      { type: "p", content: "La catégorie principale est votre signal le plus fort. Choisissez 'Restaurant', 'Pizzeria', 'Brasserie' ou la catégorie la plus précise possible. Ajoutez ensuite des catégories secondaires pour couvrir vos spécialités : 'Restaurant de fruits de mer', 'Bar à cocktails', 'Brunch'. Plus votre catégorisation est précise, plus vous apparaissez sur des requêtes spécifiques." },
      { type: "tip", content: "Regardez les catégories des 5 restaurants qui apparaissent avant vous sur Google Maps dans votre ville. C'est la meilleure façon de savoir quelles catégories Google valorise pour votre secteur et votre zone géographique." },
      { type: "h2", content: "Les photos qui font cliquer (et réserver)" },
      { type: "p", content: "En restauration, les photos sont déterminantes. Les fiches avec plus de 100 photos reçoivent 520% de demandes d'appels supplémentaires. Investissez dans des photos professionnelles de vos plats signature, de votre salle et de votre terrasse. Publiez ensuite des photos régulièrement — au minimum 2 nouvelles par semaine." },
      { type: "ul", content: ["Photo de couverture : votre plat le plus photogénique ou votre salle mise en valeur", "Plats : 10 à 20 photos des meilleurs plats de la carte, bien éclairés", "Ambiance : salle pleine, terrasse animée, soirées spéciales", "Équipe : humanisez votre établissement avec des photos de vos cuisiniers et serveurs", "Extérieur : façade de jour et de nuit pour que le client vous reconnaisse à l'arrivée"] },
      { type: "h2", content: "Google Posts : annoncer menus du jour et événements" },
      { type: "p", content: "Les Google Posts sont l'arme secrète des restaurateurs bien positionnés. Publiez votre menu du jour chaque matin, vos événements (soirée jazz, brunch dominical, menu Saint-Valentin), et vos offres spéciales. Ces publications apparaissent directement sur votre fiche et signalent à Google que votre établissement est actif." },
      { type: "h2", content: "Collecter des avis après chaque service" },
      { type: "p", content: "Le moment idéal pour demander un avis, c'est à la fin du repas, quand le client est satisfait et encore à table. Une phrase simple de votre serveur suffit : 'Si vous avez passé un bon moment, un petit avis Google nous aiderait beaucoup.' Complétez avec un QR code sur l'addition qui renvoie directement vers votre page d'avis." },
      { type: "tip", content: "En restauration, visez 5 nouveaux avis par semaine minimum. C'est le rythme qui permet de monter progressivement dans le classement Google Maps sans déclencher les filtres anti-spam de Google." },
      { type: "h2", content: "Répondre aux avis négatifs comme un pro" },
      { type: "p", content: "Un avis 2 étoiles bien géré peut devenir un argument de vente. Répondez toujours dans les 24h, reconnaissez le problème sans vous justifier à outrance, et proposez une solution concrète. Les futurs clients lisent vos réponses autant que les avis eux-mêmes — une réponse professionnelle rassure même sur un avis négatif." },
      { type: "h2", content: "Utiliser les attributs Google pour se différencier" },
      { type: "p", content: "Les attributs permettent aux clients de filtrer leurs recherches. Renseignez tous les attributs pertinents : options végétariennes, service de livraison, terrasse, wifi, accessibilité PMR, réservation en ligne. Chaque attribut correctement renseigné vous expose à des requêtes supplémentaires." },
      { type: "h2", content: "Klevano pour automatiser votre visibilité locale" },
      { type: "p", content: "Gérer sa fiche Google manuellement prend du temps — temps que vous n'avez pas quand vous gérez un service le midi et le soir. Klevano automatise la collecte d'avis, vous alerte sur les nouveaux avis à traiter et suit votre classement par rapport à vos concurrents directs. Résultat : votre fiche reste toujours optimisée sans y passer des heures." },
    ],
  },
  {
    slug: "avis-google-negatif-comment-repondre",
    title: "Comment répondre à un avis Google négatif (guide + exemples de réponses)",
    description: "Un avis négatif n'est pas une catastrophe si vous répondez correctement. Guide complet avec des exemples de réponses professionnelles pour retourner la situation.",
    date: "2026-04-03",
    category: "Collecte d'avis",
    readTime: "6 min",
    sections: [
      { type: "p", content: "Vous avez reçu un avis 1 ou 2 étoiles sur Google. La première réaction est souvent de vouloir répondre à chaud, de se défendre, voire d'ignorer. C'est exactement ce qu'il ne faut pas faire. Un avis négatif bien géré peut devenir votre meilleur argument commercial — voici comment." },
      { type: "h2", content: "Pourquoi un avis négatif bien géré est une opportunité" },
      { type: "p", content: "88% des consommateurs font davantage confiance aux entreprises qui répondent à leurs avis, qu'ils soient positifs ou négatifs. Un profil Google avec uniquement des avis 5 étoiles paraît suspect. En revanche, voir une entreprise gérer professionnellement une critique rassure les futurs clients sur votre sérieux et votre service après-vente." },
      { type: "h2", content: "Les 5 règles d'or pour répondre à un avis négatif" },
      { type: "ul", content: [
        "Attendez 30 minutes avant de répondre — ne jamais répondre à chaud",
        "Remerciez le client pour son retour, même si vous n'êtes pas d'accord",
        "Reconnaissez le problème sans l'amplifier ni vous excuser excessivement",
        "Proposez une solution concrète (rappel, remboursement, invitation à revenir)",
        "Soyez bref : 3 à 5 phrases maximum — les longues justifications aggravent la situation",
      ]},
      { type: "h2", content: "Structure d'une réponse parfaite" },
      { type: "p", content: "Une bonne réponse suit toujours la même structure : (1) Accuser réception avec empathie, (2) Reconnaître le problème spécifique, (3) S'expliquer brièvement si nécessaire, (4) Proposer de résoudre en privé. Ne déplacez jamais le débat sur la place publique — invitez le client à vous contacter directement." },
      { type: "tip", content: "Template universel : 'Bonjour [Prénom], merci pour votre retour. Nous sommes désolés que votre expérience n'ait pas été à la hauteur de vos attentes. [Explication courte si pertinente]. N'hésitez pas à nous contacter directement à [email/téléphone] pour qu'on puisse arranger ça. Cordialement, [Prénom] — [Entreprise]'" },
      { type: "h2", content: "Exemples de réponses par secteur" },
      { type: "ul", content: [
        "Restaurant (plat froid) : 'Bonjour Marie, vous avez tout à fait raison et nous nous en excusons. Ce soir-là, nous étions particulièrement chargés, ce qui n'excuse pas la qualité du service. Contactez-nous au [tel] — nous serions heureux de vous accueillir à nouveau dans de meilleures conditions.'",
        "Artisan (délai non respecté) : 'Bonjour Pierre, votre retour est légitime. Le délai a effectivement été plus long que prévu en raison d'un problème d'approvisionnement dont nous aurions dû vous informer plus tôt. Pour tout futur projet, appelez-nous directement — nous ferons mieux.'",
        "Commerce (produit défectueux) : 'Bonjour, nous sommes vraiment désolés pour ce désagrément. Passez en boutique avec votre ticket de caisse, nous échangerons immédiatement votre article. Ce type d'incident n'est pas représentatif de notre standard habituel.'",
      ]},
      { type: "h2", content: "Ce qu'il ne faut JAMAIS faire" },
      { type: "ul", content: [
        "Accuser le client de mentir ou d'exagérer — même si c'est vrai",
        "Se justifier longuement avec des détails techniques ou internes",
        "Répondre avec une formule générique copiée-collée",
        "Ignorer l'avis — Google voit le taux de réponse du propriétaire",
        "Supprimer votre réponse après l'avoir postée — cela crée de la méfiance",
      ]},
      { type: "h2", content: "Comment demander la suppression d'un faux avis" },
      { type: "p", content: "Si vous êtes certain qu'un avis est faux (concurrent malveillant, personne qui n'a jamais été cliente), signalez-le à Google via le bouton 'Signaler un avis' sur votre fiche. Joignez des preuves si possible (dates, réservations). Google peut prendre 2 à 4 semaines pour statuer — en attendant, répondez à l'avis de façon factuelle et professionnelle." },
      { type: "h2", content: "Automatisez vos réponses avec Klevano" },
      { type: "p", content: "Répondre à chaque avis manuellement prend du temps. Klevano génère des suggestions de réponse personnalisées pour chaque avis — positif ou négatif — en tenant compte du contenu spécifique du commentaire. Vous validez en un clic ou ajustez légèrement. Résultat : 100% de taux de réponse sans y passer des heures." },
    ],
  },
  {
    slug: "google-my-business-categories-choisir",
    title: "Catégories Google My Business : comment bien les choisir pour booster votre classement",
    description: "Le choix des catégories GMB est le facteur de classement le plus sous-estimé. Découvrez comment choisir vos catégories principale et secondaires pour dominer votre secteur.",
    date: "2026-04-05",
    category: "Optimisation GMB",
    readTime: "5 min",
    sections: [
      { type: "p", content: "La catégorie principale de votre fiche Google My Business est probablement le signal SEO le plus puissant — et le plus sous-estimé — du référencement local. Beaucoup d'entreprises choisissent une catégorie trop générique et passent à côté de dizaines de requêtes qualifiées chaque jour." },
      { type: "h2", content: "Pourquoi la catégorie principale est le signal le plus fort" },
      { type: "p", content: "Google utilise la catégorie principale pour décider sur quelles requêtes vous montrer. Si vous êtes une pizzeria et que vous avez sélectionné 'Restaurant' comme catégorie principale, vous serez en compétition avec tous les restaurants de votre ville — et vous perdrez contre les pizzerias qui ont choisi la bonne catégorie. La précision est récompensée." },
      { type: "h2", content: "Comment Google utilise les catégories pour le classement" },
      { type: "ul", content: [
        "Catégorie principale = signal le plus fort pour les requêtes génériques",
        "Catégories secondaires = visibilité supplémentaire sur des requêtes spécifiques",
        "Google peut suggérer des catégories basées sur vos posts, photos et avis",
        "Changer de catégorie principale peut faire baisser temporairement votre classement",
      ]},
      { type: "h2", content: "Stratégie pour choisir sa catégorie principale" },
      { type: "p", content: "Choisissez la catégorie la plus précise qui décrit votre activité principale. Une boulangerie-pâtisserie : choisissez 'Boulangerie' si vous vendez surtout du pain, 'Pâtisserie' si vos gâteaux sont votre produit phare. Évitez les catégories trop larges comme 'Commerce de détail' ou 'Entreprise locale' — elles ne vous aideront pas à apparaître sur des requêtes spécifiques." },
      { type: "tip", content: "Testez votre catégorie actuelle : cherchez '[votre activité] [votre ville]' sur Google Maps en navigation privée. Si vous n'apparaissez pas dans les 10 premiers résultats alors que vous avez des avis, votre catégorie principale est probablement trop générique." },
      { type: "h2", content: "Comment utiliser les catégories secondaires (jusqu'à 9)" },
      { type: "p", content: "Les catégories secondaires vous permettent d'apparaître sur des requêtes connexes à votre activité principale. Un restaurant peut ajouter 'Bar', 'Salle de réception', 'Traiteur'. Un coiffeur peut ajouter 'Institut de beauté', 'Salon de manucure'. Utilisez toutes les catégories qui décrivent réellement vos services — pas de catégories sans rapport." },
      { type: "h2", content: "Les meilleures catégories par secteur" },
      { type: "ul", content: [
        "Restauration : Pizzeria / Restaurant français / Brasserie / Bar à cocktails / Salon de thé",
        "Commerce : Boulangerie / Épicerie fine / Fleuriste / Librairie / Caviste",
        "Artisanat : Plombier / Électricien / Peintre / Menuisier / Serrurier",
        "Santé : Médecin généraliste / Kinésithérapeute / Dentiste / Ostéopathe / Pharmacie",
        "Beauté : Coiffeur / Institut de beauté / Barbier / Salon de nail art / Spa",
      ]},
      { type: "h2", content: "Espionner les catégories de vos concurrents" },
      { type: "p", content: "La méthode la plus rapide pour trouver les meilleures catégories : regardez celles des 5 premiers concurrents sur Google Maps dans votre secteur. Sur mobile, appuyez sur la fiche d'un concurrent et cherchez la section 'Catégories'. Sur desktop, les catégories apparaissent sous le nom de l'établissement. Notez les catégories communes — ce sont celles que Google valorise dans votre niche." },
      { type: "h2", content: "Erreurs à éviter" },
      { type: "ul", content: [
        "Choisir une catégorie inexacte pour apparaître sur plus de requêtes — Google pénalise cela",
        "Avoir plus de 5 catégories secondaires sans rapport direct avec votre activité",
        "Changer de catégorie principale trop souvent — stabilité = confiance pour Google",
        "Oublier de mettre à jour vos catégories si votre activité évolue",
      ]},
      { type: "h2", content: "Optimisez toute votre fiche avec Klevano" },
      { type: "p", content: "Les catégories ne sont que l'un des 50+ signaux que Google prend en compte pour le classement local. Klevano analyse l'intégralité de votre fiche — catégories, photos, avis, posts, description — et vous donne un score avec les actions prioritaires. Commencez gratuitement sur klevano.com." },
    ],
  },
  {
    slug: "google-posts-guide-complet",
    title: "Google Posts : le guide complet pour booster votre fiche GMB en 2026",
    description: "Les Google Posts sont la fonctionnalité la plus sous-utilisée de Google My Business. Découvrez comment les utiliser pour attirer plus de clients et améliorer votre référencement local.",
    date: "2026-04-07",
    category: "Optimisation GMB",
    readTime: "7 min",
    sections: [
      { type: "p", content: "Moins de 10% des entreprises locales utilisent les Google Posts régulièrement. Pourtant, cette fonctionnalité gratuite permet de publier du contenu directement sur votre fiche Google — visible par tous les internautes qui vous cherchent sur Maps ou la Recherche Google. C'est de la publicité gratuite au moment le plus important : quand le client vous cherche déjà." },
      { type: "h2", content: "Qu'est-ce qu'un Google Post et pourquoi ça compte" },
      { type: "p", content: "Un Google Post est une mini-publication (texte + image + bouton d'action) qui apparaît dans le panneau de votre fiche Google My Business. Elle est visible pendant 7 jours (sauf les événements, visibles jusqu'à leur date de fin). Google prend en compte la régularité de publication comme signal d'activité — une fiche qui publie régulièrement est considérée comme plus fiable." },
      { type: "h2", content: "Les 4 types de posts Google" },
      { type: "ul", content: [
        "Actualité : informations générales, nouveautés, changements dans votre entreprise",
        "Événement : soirées, ateliers, concerts, portes ouvertes — avec date de début et de fin",
        "Offre : promotions, soldes, codes promo — idéal pour générer de l'urgence",
        "Produit : mettre en avant un produit ou service spécifique avec prix et lien",
      ]},
      { type: "h2", content: "Fréquence idéale de publication" },
      { type: "p", content: "L'idéal est de publier 2 à 3 Google Posts par semaine. Si c'est trop ambitieux pour commencer, visez au minimum 1 post par semaine — c'est le seuil en dessous duquel Google considère votre fiche comme inactive. Créez un calendrier éditorial simple : une actualité, une offre et un événement par mois, avec des posts produits en complément." },
      { type: "tip", content: "Astuce : créez 4 posts d'un coup le lundi matin pour avoir de la matière toute la semaine. Google Space (l'interface GMB sur mobile) permet de programmer des posts à l'avance." },
      { type: "h2", content: "Comment rédiger un post qui génère des clics" },
      { type: "p", content: "Un Google Post efficace suit une structure simple : accroche forte en première ligne (elle seule est visible avant le 'Voir plus'), 2-3 phrases de valeur, et un bouton d'action clair. Les posts avec image reçoivent 94% de clics supplémentaires. Choisissez une image lumineuse, sans trop de texte superposé." },
      { type: "ul", content: [
        "Accroche : commencez par le bénéfice, pas par votre nom ('Profitez de -20%...' plutôt que 'Chez Dupont, nous vous proposons...')",
        "Corps : 150 à 300 caractères idéaux — allez à l'essentiel",
        "CTA : 'Réserver', 'En savoir plus', 'Appeler', 'Acheter' selon l'objectif",
        "Image : 1200x900px minimum, lumineuse, avec du contraste",
      ]},
      { type: "h2", content: "Idées de posts pour chaque secteur" },
      { type: "ul", content: [
        "Restaurant : menu du jour, nouveau plat, soirée à thème, fermeture exceptionnelle",
        "Commerce : nouvelle collection, promotion du mois, produit coup de cœur, anniversaire du magasin",
        "Artisan : avant/après chantier, nouveau service proposé, conseil pratique, zone d'intervention",
        "Santé/Beauté : nouveau soin, conseil bien-être, disponibilités exceptionnelles, promo sur rdv",
      ]},
      { type: "h2", content: "Erreurs courantes à éviter" },
      { type: "ul", content: [
        "Publier puis ne plus rien publier pendant des semaines — la régularité est tout",
        "Utiliser des images floues ou en mauvaise résolution",
        "Oublier le bouton d'action — sans CTA, le post ne génère pas de clics",
        "Copier-coller le même post chaque semaine — Google valorise la variété",
      ]},
      { type: "h2", content: "Mesurer l'impact de vos posts" },
      { type: "p", content: "Dans votre tableau de bord Google My Business, la section 'Performances' vous indique le nombre de vues et de clics sur vos posts. Analysez quels types de posts génèrent le plus d'engagement dans votre secteur et ajustez votre stratégie en conséquence. Klevano centralise ces données et vous envoie un rapport mensuel de performance de votre fiche." },
    ],
  },
  {
    slug: "audit-fiche-google-my-business",
    title: "Comment auditer votre fiche Google My Business en 10 points (checklist complète)",
    description: "Évaluez la performance de votre fiche Google My Business avec cette checklist en 10 points. Identifiez vos points faibles et passez à l'action immédiatement.",
    date: "2026-04-08",
    category: "Optimisation GMB",
    readTime: "6 min",
    sections: [
      { type: "p", content: "Vous avez une fiche Google My Business, mais êtes-vous sûr qu'elle est vraiment optimisée ? La plupart des commerçants ont une fiche à 40-50% de son potentiel. Voici une checklist complète en 10 points pour identifier exactement ce qui vous empêche d'apparaître en tête de Google Maps." },
      { type: "h2", content: "Pourquoi auditer sa fiche GMB régulièrement" },
      { type: "p", content: "Google My Business évolue constamment : nouvelles fonctionnalités, changements d'algorithme, informations qui deviennent obsolètes. Un audit trimestriel permet de s'assurer que votre fiche reste compétitive. C'est aussi l'occasion de comparer votre fiche avec celle de vos concurrents et d'identifier les opportunités manquées." },
      { type: "h2", content: "Point 1 — Informations de base (NAP)" },
      { type: "p", content: "Vérifiez que votre Nom, Adresse et Téléphone (NAP) sont exacts et identiques sur toutes vos présences en ligne. Une incohérence entre votre fiche GMB et votre site web envoie un signal négatif à Google. Vérifiez aussi que vos horaires sont à jour, y compris les jours fériés et les horaires exceptionnels." },
      { type: "h2", content: "Point 2 — Vérification de la fiche" },
      { type: "p", content: "Votre fiche est-elle vérifiée ? Une fiche non vérifiée ne peut pas apparaître dans le pack local. Si ce n'est pas fait, demandez la vérification via Google My Business — le processus prend généralement 5 à 14 jours par courrier postal ou quelques minutes par vidéo." },
      { type: "h2", content: "Point 3 — Catégories" },
      { type: "p", content: "Avez-vous choisi la catégorie principale la plus précise possible ? Avez-vous utilisé des catégories secondaires pertinentes ? Comparez avec les 5 premiers concurrents sur Maps — s'ils ont des catégories que vous n'avez pas, ajoutez-les si elles correspondent à vos services." },
      { type: "h2", content: "Point 4 — Photos" },
      { type: "ul", content: [
        "Avez-vous au moins 10 photos de qualité sur votre fiche ?",
        "La photo de couverture est-elle attractive et représentative ?",
        "Avez-vous publié une nouvelle photo dans les 30 derniers jours ?",
        "Avez-vous des photos de l'extérieur, intérieur, produits/services ET de l'équipe ?",
      ]},
      { type: "h2", content: "Point 5 — Avis clients" },
      { type: "p", content: "Combien d'avis avez-vous et quelle est votre note ? Avez-vous répondu à tous vos avis (positifs ET négatifs) ? Avez-vous reçu un avis dans les 30 derniers jours ? La fraîcheur des avis est un signal fort pour Google — si votre dernier avis date de 6 mois, il est temps de relancer votre collecte." },
      { type: "h2", content: "Point 6 — Description d'entreprise" },
      { type: "p", content: "Votre description fait-elle plus de 200 caractères ? Intègre-t-elle naturellement vos mots clés principaux (activité + ville) ? Mentionne-t-elle vos différenciateurs (depuis 20 ans, certifié, livraison gratuite...) ? La description est souvent négligée alors qu'elle est lue par les clients avant de choisir de vous appeler." },
      { type: "h2", content: "Point 7 — Google Posts" },
      { type: "p", content: "Avez-vous publié un Google Post dans les 7 derniers jours ? Si non, votre fiche est considérée comme inactive. Planifiez dès maintenant un post pour cette semaine — une actualité simple ou une offre en cours suffit." },
      { type: "h2", content: "Point 8 — Questions & Réponses" },
      { type: "p", content: "La section Q&R de votre fiche est souvent ignorée alors que des clients y posent des questions auxquelles n'importe qui peut répondre (y compris vos concurrents). Prenez le contrôle : posez vous-même les 5 questions les plus fréquentes que vos clients vous posent et répondez-y." },
      { type: "h2", content: "Point 9 — Cohérence avec votre site web" },
      { type: "p", content: "Votre site web mentionne-t-il votre adresse et votre numéro de téléphone exactement comme sur votre fiche GMB ? Avez-vous le Schema Markup LocalBusiness sur votre site ? Google croise ces informations pour valider la légitimité de votre fiche." },
      { type: "h2", content: "Point 10 — Insights et performances" },
      { type: "p", content: "Regardez vos statistiques Google My Business : combien de fois votre fiche a-t-elle été vue ce mois-ci ? Combien d'appels, de clics vers votre site, de demandes d'itinéraire ? Si ces chiffres stagnent ou baissent, c'est le signal qu'il faut agir sur l'un des 9 points précédents." },
      { type: "h2", content: "Automatisez votre optimisation avec Klevano" },
      { type: "p", content: "Cet audit manuel prend 30 à 45 minutes. Avec Klevano, vous disposez d'un tableau de bord qui suit en temps réel votre score d'optimisation, vous alerte quand un avis nécessite une réponse, et vous suggère les actions prioritaires semaine après semaine. Commencez gratuitement sur klevano.com." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}
